<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_product = $block->getProduct(); 


if (!empty($_product->getAttributeDefaultValue('product_cms_block')))
{
  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($_product->getAttributeDefaultValue('product_cms_block'))->toHtml();
}
?>


